// Centralised content tool TypeScript types.
// Import from here — do not redefine inline in components.

export interface ContentItem {
  type:               'post' | 'topic'
  id:                 string
  clientId:           string
  clientName:         string
  status:             string
  targetKeyword:      string | null
  title:              string | null
  topicText:          string | null
  wordCount:          number | null
  headingCount:       number | null
  internalLinks:      number | null
  generatedAt:        string
  generatedBy:        string
  publishedUrl:       string | null
  generateByDate:     string | null
  targetPublishDate:  string | null
  rationale:          string | null
  wpPostId:           number | null
  wpSiteUrl:          string | null
  // Topic-only
  keywordOpportunity: string | null
  rankingStrategy:    string | null
  audienceIntent:     string | null
  whyNow:             string | null
  competitionLevel:   string | null
  generationError:    string | null
  suggestedTitle:     string | null
  searchVolume:       number | null
  keywordDifficulty:  number | null
  postId:             string | null
  seoBrief:           SeoBrief | null
  // Post-only
  seoScore:           SeoScore | null
  schemaType:         string | null
  excerpt:            string | null
}

export interface SiteOption {
  connectionId:  string
  siteUrl:       string
  siteName:      string
  clientId:      string
  clientName:    string
  connectorType?: string
}

export interface ClientScheduleSettings {
  schedule_frequency:    string | null
  schedule_day_of_week:  number | null
  monthly_publish_day:   number | null
  posts_per_run:         number
  topics_per_run:        number
  weeks_ahead:           number
  schedule_start_date:   string | null
  auto_generate:         boolean
  connection_id:         string | null
  default_author_id:     number | null
  post_structure:        string
  target_length:         number
  publish_time:          string | null
}

export interface ClientBrandDna {
  business_background: string
  services:            string
  target_audience:     string
  geographic_focus:    string
  brand_voice:         string
  phone_number:        string
  cta_list:            string
  sitemap_urls:        string[]
  manual_link_urls:    string[]
  eeat_data:           EeatData | null
}

// E-E-A-T trust signals — stored as JSONB in content_settings.eeat_data
export interface EeatData {
  years_in_business:      string
  licenses:               string
  insurance:              string
  awards:                 string
  review_count:           string
  owner_details:          string
  team_experience:        string
  guarantees:             string
  brands_used:            string
  financing_options:      string
  emergency_availability: boolean
  warranties:             string
  case_studies:           string
  before_after_proof:     string
  common_objections:      string
}

// SEO Brief — stored as JSONB in content_topics.seo_brief.
// Generated by AI after topic approval, before post generation.
export interface SeoBrief {
  primary_keyword:         string
  secondary_keywords:      string[]
  search_intent:           'informational' | 'commercial' | 'local_service' | 'comparison' | 'cost_pricing' | 'how_to' | 'faq' | 'emergency'
  funnel_stage:            'awareness' | 'consideration' | 'decision'
  target_audience:         string
  suggested_slug:          string
  title_tag:               string
  alternative_titles:      string[]
  meta_description:        string
  h1:                      string
  h2_outline:              string[]
  internal_link_targets:   string[]
  external_source_types:   string[]
  local_seo_angle:         string
  faq_opportunities:       string[]
  schema_type:             'BlogPosting' | 'FAQPage' | 'HowTo' | 'Service' | 'LocalBusiness' | null
  content_gap_notes:       string
  unique_angle:            string
  cta_text:                string
  expert_review_flag:      boolean
  expert_review_reason:    string | null
  cannibalization_warning: string | null
  image_concept:           string
  alt_text:                string
  word_count_target:       number
}

// SEO QA score — stored as JSONB in content_posts.seo_score.
// Computed locally after post generation; no extra AI call.
export interface SeoScore {
  overall:              number
  keyword_in_title:     boolean
  keyword_in_intro:     boolean
  keyword_in_headings:  boolean
  intent_match:         boolean
  heading_structure:    boolean
  internal_links_count: number
  local_relevance:      boolean
  cta_present:          boolean
  faq_present:          boolean
  meta_present:         boolean
  eat_signals:          boolean
  word_count_on_target: boolean
  over_optimised:       boolean
  duplicate_warning:    boolean
  issues:               string[]
  warnings:             string[]
}
