const test = require('node:test'); const assert = require('node:assert/strict')
const path = require('path'); const src = p => path.join(process.env.WT, 'src', p)
const { splitPhrases } = require(src('lib/content/phrases.ts'))
const { serviceAreaLine } = require(src('lib/content/serviceAreas.ts'))
const { locationCandidates, parseServices, geoPhrase } = require(src('lib/content/researchSeeds.ts'))
const L = require(src('lib/content/lengthRules.ts'))

test('splitPhrases keeps a place with its state', () => {
  assert.deepEqual(splitPhrases('Melbourne, FL, Palm Bay, FL'), ['Melbourne, FL', 'Palm Bay, FL'])
  assert.deepEqual(splitPhrases('Springfield, MA'), ['Springfield, MA'])
  assert.deepEqual(splitPhrases('Florida, Georgia'), ['Florida', 'Georgia'])
  assert.deepEqual(splitPhrases('Washington, DC'), ['Washington, DC'])
  assert.deepEqual(splitPhrases('Melbourne, Florida, United States'), ['Melbourne, Florida'])
  assert.deepEqual(splitPhrases('gutter guards (mesh, micro-mesh), roofing'), ['gutter guards (mesh, micro-mesh)', 'roofing'])
  assert.deepEqual(splitPhrases('Roof Repair, roof repair'), ['Roof Repair'])
  assert.deepEqual(splitPhrases(''), []); assert.deepEqual(splitPhrases(null), [])
  assert.deepEqual(splitPhrases('Los Angeles\nOrange County; Riverside'), ['Los Angeles', 'Orange County', 'Riverside'])
})
test('serviceAreaLine names every area, primary first', () => {
  assert.equal(serviceAreaLine('Melbourne, FL, Palm Bay, FL, Cocoa, FL'),
    'Service areas: Melbourne, FL (primary — lead with this), then Palm Bay, FL, Cocoa, FL')
  assert.equal(serviceAreaLine('Springfield, MA'), 'Service area: Springfield, MA')
  assert.equal(serviceAreaLine(''), null)
})
test('locationCandidates passes the state through', () => {
  assert.deepEqual(locationCandidates('Springfield, MA'), ['Springfield, MA'])
  assert.deepEqual(locationCandidates('Melbourne, FL, Palm Bay, FL'), ['Melbourne, FL', 'Palm Bay, FL'])
  assert.deepEqual(locationCandidates('Brevard County, FL (based in Cocoa, FL)'), ['Brevard County, FL'])
  assert.deepEqual(locationCandidates('nationwide'), [])
  assert.deepEqual(locationCandidates('Los Angeles and Tri-County area').slice(0, 1), ['Los Angeles'])
})
test('parseServices and geoPhrase', () => {
  assert.deepEqual(parseServices('gutter guards (mesh, micro-mesh), roofing, x'), ['gutter guards (mesh, micro-mesh)', 'roofing'])
  assert.equal(geoPhrase(null, 'Melbourne, FL, Palm Bay, FL'), 'Melbourne')
  assert.equal(geoPhrase({ name: 'Springfield,Massachusetts,United States' }, 'x'), 'Springfield')
})
test('length budget and tighten verdicts', () => {
  const b = L.lengthBudget(1500)
  assert.deepEqual(b, { target: 1500, floor: 1350, ceiling: 1725 })
  assert.equal(L.lengthBudget(null).target, 1500); assert.equal(L.lengthBudget(100).target, 300)
  assert.equal(L.isOverLength(b, 1726), true); assert.equal(L.isOverLength(b, 1725), false)
  const html = n => '<h2>a</h2><p><a href="https://x.com/a">x</a></p>'.repeat(n)
  const d = (words, h, title = 'T') => ({ words, html: h, title })
  assert.equal(L.judgeTightened(b, d(2700, html(4)), d(1300, html(4))).accept, true, 'closer, above 75% floor')
  assert.equal(L.judgeTightened(b, d(2700, html(4)), d(1100, html(4))).accept, false, 'below 75% of target')
  assert.equal(L.judgeTightened(b, d(1800, html(4)), d(1200, html(4))).accept, false, 'further from target')
  assert.equal(L.judgeTightened(b, d(2700, html(4)), d(1500, html(3))).accept, false, 'lost a link')
  assert.equal(L.judgeTightened(b, d(2700, html(4)), d(1500, html(4), '')).accept, false, 'no title')
  assert.match(L.lengthInstruction(b), /between 1350 and 1725 words/)
})
